name: Hello World ceedling

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'

    - name: Run ceedlings tests
      run: ceedling test::Hello

      
